<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated data snapshot for `appointments` (10 rows).
 * Regenerated from the live `velto_admin` database.
 */
class AppointmentSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('appointments')->truncate();

        $rows = [
            [
                'id' => 1,
                'customer_id' => 12,
                'worker_id' => null,
                'vehicle_id' => 6,
                'wash_package_id' => 1,
                'time_slot_id' => 85,
                'wallet_transaction_id' => 28,
                'status' => 'cancelled',
                'scheduled_at' => '2026-06-09 09:00:00',
                'address_label' => 'Home — Olaya',
                'latitude' => '24.7136000',
                'longitude' => '46.6753000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Toyota Camry · ABC 1234',
                'add_ons' => '[{"id": 1, "name": "Tire shine", "name_ar": "تلميع إطارات", "extra_price": 15}]',
                'base_price' => '99.00',
                'addons_total' => '15.00',
                'total_price' => '114.00',
                'payment_method' => 'wallet',
                'payment_status' => 'refunded',
                'notes' => null,
                'cancelled_at' => '2026-06-09 07:57:09',
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-06-09 07:57:08',
                'updated_at' => '2026-06-09 07:57:09',
            ],
            [
                'id' => 2,
                'customer_id' => 13,
                'worker_id' => null,
                'vehicle_id' => 7,
                'wash_package_id' => 1,
                'time_slot_id' => 90,
                'wallet_transaction_id' => 31,
                'status' => 'confirmed',
                'scheduled_at' => '2026-06-09 18:30:00',
                'address_label' => null,
                'latitude' => null,
                'longitude' => null,
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Lexus RX · XYZ 9',
                'add_ons' => '[]',
                'base_price' => '99.00',
                'addons_total' => '0.00',
                'total_price' => '99.00',
                'payment_method' => 'wallet',
                'payment_status' => 'paid',
                'notes' => null,
                'cancelled_at' => null,
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-06-09 07:58:11',
                'updated_at' => '2026-06-09 07:58:12',
            ],
            [
                'id' => 3,
                'customer_id' => 14,
                'worker_id' => 6,
                'vehicle_id' => 8,
                'wash_package_id' => 1,
                'time_slot_id' => 87,
                'wallet_transaction_id' => 33,
                'status' => 'completed',
                'scheduled_at' => '2026-06-24 17:00:00',
                'address_label' => null,
                'latitude' => null,
                'longitude' => null,
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Kia K5 · AAA 1',
                'add_ons' => '[]',
                'base_price' => '99.00',
                'addons_total' => '0.00',
                'total_price' => '99.00',
                'payment_method' => 'wallet',
                'payment_status' => 'paid',
                'notes' => null,
                'cancelled_at' => null,
                'completed_at' => '2026-06-24 07:45:26',
                'accepted_at' => '2026-06-24 07:43:52',
                'started_at' => '2026-06-24 07:44:09',
                'arrived_at' => '2026-06-24 07:44:31',
                'work_started_at' => '2026-06-24 07:44:43',
                'created_at' => '2026-06-09 08:44:11',
                'updated_at' => '2026-06-24 07:45:26',
            ],
            [
                'id' => 4,
                'customer_id' => 10,
                'worker_id' => 6,
                'vehicle_id' => 10,
                'wash_package_id' => 1,
                'time_slot_id' => 1,
                'wallet_transaction_id' => 35,
                'status' => 'completed',
                'scheduled_at' => '2026-07-04 09:00:00',
                'address_label' => 'المنزل - الملقا',
                'latitude' => '24.8200000',
                'longitude' => '46.6300000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '20.00',
                'addons_total' => '0.00',
                'total_price' => '20.00',
                'payment_method' => 'wallet',
                'payment_status' => 'paid',
                'notes' => 'حجز اختبار',
                'cancelled_at' => null,
                'completed_at' => '2026-07-03 06:38:08',
                'accepted_at' => '2026-07-03 06:38:07',
                'started_at' => '2026-07-03 06:38:08',
                'arrived_at' => '2026-07-03 06:38:08',
                'work_started_at' => '2026-07-03 06:38:08',
                'created_at' => '2026-07-03 06:29:42',
                'updated_at' => '2026-07-03 06:38:08',
            ],
            [
                'id' => 5,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 11,
                'wash_package_id' => 1,
                'time_slot_id' => 8,
                'wallet_transaction_id' => 36,
                'status' => 'confirmed',
                'scheduled_at' => '2026-07-05 10:30:00',
                'address_label' => 'الرياض — المهدية',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'تويوتا Camry · 1234',
                'add_ons' => '[]',
                'base_price' => '20.00',
                'addons_total' => '0.00',
                'total_price' => '20.00',
                'payment_method' => 'wallet',
                'payment_status' => 'paid',
                'notes' => null,
                'cancelled_at' => null,
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 07:45:09',
                'updated_at' => '2026-07-03 07:45:09',
            ],
            [
                'id' => 6,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 10,
                'wash_package_id' => 1,
                'time_slot_id' => 1,
                'wallet_transaction_id' => 38,
                'status' => 'cancelled',
                'scheduled_at' => '2026-07-04 09:00:00',
                'address_label' => 'اختبار',
                'latitude' => '24.8000000',
                'longitude' => '46.6000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '20.00',
                'addons_total' => '0.00',
                'total_price' => '20.00',
                'payment_method' => 'wallet',
                'payment_status' => 'refunded',
                'notes' => null,
                'cancelled_at' => '2026-07-03 08:49:26',
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 08:47:44',
                'updated_at' => '2026-07-03 08:49:26',
            ],
            [
                'id' => 7,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 10,
                'wash_package_id' => 2,
                'time_slot_id' => 2,
                'wallet_transaction_id' => null,
                'status' => 'cancelled',
                'scheduled_at' => '2026-07-04 10:30:00',
                'address_label' => 'اختبار',
                'latitude' => '24.8000000',
                'longitude' => '46.6000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Interior detail',
                'service_name_ar' => 'تنظيف داخلي',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '30.00',
                'addons_total' => '0.00',
                'total_price' => '30.00',
                'payment_method' => 'card',
                'payment_status' => 'refund_pending',
                'notes' => null,
                'cancelled_at' => '2026-07-03 08:49:26',
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 08:47:44',
                'updated_at' => '2026-07-03 08:49:26',
            ],
            [
                'id' => 8,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 10,
                'wash_package_id' => 1,
                'time_slot_id' => 1,
                'wallet_transaction_id' => null,
                'status' => 'cancelled',
                'scheduled_at' => '2026-07-04 09:00:00',
                'address_label' => 'x',
                'latitude' => '24.8000000',
                'longitude' => '46.6000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '20.00',
                'addons_total' => '0.00',
                'total_price' => '20.00',
                'payment_method' => 'card',
                'payment_status' => 'pending',
                'notes' => null,
                'cancelled_at' => '2026-07-03 08:48:34',
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 08:48:33',
                'updated_at' => '2026-07-03 08:48:34',
            ],
            [
                'id' => 9,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 10,
                'wash_package_id' => 3,
                'time_slot_id' => 1,
                'wallet_transaction_id' => null,
                'status' => 'pending',
                'scheduled_at' => '2026-07-04 09:00:00',
                'address_label' => 'الرياض',
                'latitude' => '24.8000000',
                'longitude' => '46.6000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Full detail',
                'service_name_ar' => 'تنظيف متكامل',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '40.00',
                'addons_total' => '0.00',
                'total_price' => '40.00',
                'payment_method' => 'card',
                'payment_status' => 'pending',
                'notes' => null,
                'cancelled_at' => null,
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 08:52:27',
                'updated_at' => '2026-07-03 08:52:27',
            ],
            [
                'id' => 10,
                'customer_id' => 10,
                'worker_id' => null,
                'vehicle_id' => 10,
                'wash_package_id' => 1,
                'time_slot_id' => 7,
                'wallet_transaction_id' => null,
                'status' => 'pending',
                'scheduled_at' => '2026-07-05 09:00:00',
                'address_label' => 'الرياض — المهدية',
                'latitude' => '0.0000000',
                'longitude' => '0.0000000',
                'area_id' => null,
                'zone_id' => null,
                'service_name' => 'Express exterior wash',
                'service_name_ar' => 'غسيل خارجي سريع',
                'vehicle_label' => 'Toyota Camry · RXA 4821',
                'add_ons' => '[]',
                'base_price' => '20.00',
                'addons_total' => '0.00',
                'total_price' => '20.00',
                'payment_method' => 'card',
                'payment_status' => 'pending',
                'notes' => null,
                'cancelled_at' => null,
                'completed_at' => null,
                'accepted_at' => null,
                'started_at' => null,
                'arrived_at' => null,
                'work_started_at' => null,
                'created_at' => '2026-07-03 10:06:07',
                'updated_at' => '2026-07-03 10:06:07',
            ],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('appointments')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
