<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated data snapshot for `countries` (16 rows).
 * Regenerated from the live `velto_admin` database.
 */
class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('countries')->truncate();

        $rows = [
            [
                'id' => 1,
                'code' => 'SA',
                'dial' => '+966',
                'flag' => '🇸🇦',
                'name' => 'Saudi Arabia',
                'name_ar' => 'السعودية',
                'phone_length' => 9,
                'sort_order' => 0,
                'is_active' => 1,
                'is_default' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 2,
                'code' => 'AE',
                'dial' => '+971',
                'flag' => '🇦🇪',
                'name' => 'United Arab Emirates',
                'name_ar' => 'الإمارات',
                'phone_length' => 9,
                'sort_order' => 1,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 3,
                'code' => 'KW',
                'dial' => '+965',
                'flag' => '🇰🇼',
                'name' => 'Kuwait',
                'name_ar' => 'الكويت',
                'phone_length' => 8,
                'sort_order' => 2,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 4,
                'code' => 'QA',
                'dial' => '+974',
                'flag' => '🇶🇦',
                'name' => 'Qatar',
                'name_ar' => 'قطر',
                'phone_length' => 8,
                'sort_order' => 3,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 5,
                'code' => 'BH',
                'dial' => '+973',
                'flag' => '🇧🇭',
                'name' => 'Bahrain',
                'name_ar' => 'البحرين',
                'phone_length' => 8,
                'sort_order' => 4,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 6,
                'code' => 'OM',
                'dial' => '+968',
                'flag' => '🇴🇲',
                'name' => 'Oman',
                'name_ar' => 'عُمان',
                'phone_length' => 8,
                'sort_order' => 5,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 7,
                'code' => 'JO',
                'dial' => '+962',
                'flag' => '🇯🇴',
                'name' => 'Jordan',
                'name_ar' => 'الأردن',
                'phone_length' => 9,
                'sort_order' => 6,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 8,
                'code' => 'EG',
                'dial' => '+20',
                'flag' => '🇪🇬',
                'name' => 'Egypt',
                'name_ar' => 'مصر',
                'phone_length' => 10,
                'sort_order' => 7,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 9,
                'code' => 'IQ',
                'dial' => '+964',
                'flag' => '🇮🇶',
                'name' => 'Iraq',
                'name_ar' => 'العراق',
                'phone_length' => 10,
                'sort_order' => 8,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 10,
                'code' => 'LB',
                'dial' => '+961',
                'flag' => '🇱🇧',
                'name' => 'Lebanon',
                'name_ar' => 'لبنان',
                'phone_length' => 8,
                'sort_order' => 9,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 11,
                'code' => 'YE',
                'dial' => '+967',
                'flag' => '🇾🇪',
                'name' => 'Yemen',
                'name_ar' => 'اليمن',
                'phone_length' => 9,
                'sort_order' => 10,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 12,
                'code' => 'TR',
                'dial' => '+90',
                'flag' => '🇹🇷',
                'name' => 'Türkiye',
                'name_ar' => 'تركيا',
                'phone_length' => 10,
                'sort_order' => 11,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 13,
                'code' => 'PK',
                'dial' => '+92',
                'flag' => '🇵🇰',
                'name' => 'Pakistan',
                'name_ar' => 'باكستان',
                'phone_length' => 10,
                'sort_order' => 12,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 14,
                'code' => 'IN',
                'dial' => '+91',
                'flag' => '🇮🇳',
                'name' => 'India',
                'name_ar' => 'الهند',
                'phone_length' => 10,
                'sort_order' => 13,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 15,
                'code' => 'GB',
                'dial' => '+44',
                'flag' => '🇬🇧',
                'name' => 'United Kingdom',
                'name_ar' => 'المملكة المتحدة',
                'phone_length' => 10,
                'sort_order' => 14,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 16,
                'code' => 'US',
                'dial' => '+1',
                'flag' => '🇺🇸',
                'name' => 'United States',
                'name_ar' => 'الولايات المتحدة',
                'phone_length' => 10,
                'sort_order' => 15,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('countries')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
