<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated data snapshot for `customers` (15 rows).
 * Regenerated from the live `velto_admin` database.
 */
class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('customers')->truncate();

        $rows = [
            [
                'id' => 1,
                'name' => 'Hani Yousif',
                'phone' => '+966500000001',
                'email' => 'hani@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '177.00',
                'joined_at' => '2026-02-09 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 18:46:59',
            ],
            [
                'id' => 2,
                'name' => 'Sara Al Otaibi',
                'phone' => '+966500000002',
                'email' => 'sara@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '177.00',
                'joined_at' => '2026-03-02 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 18:46:59',
            ],
            [
                'id' => 3,
                'name' => 'Faisal Al Saud',
                'phone' => '+966500000003',
                'email' => 'faisal@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '177.00',
                'joined_at' => '2026-03-05 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 4,
                'name' => 'Layla Al Harbi',
                'phone' => '+966500000004',
                'email' => 'layla@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '177.00',
                'joined_at' => '2026-03-28 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 5,
                'name' => 'Omar Al Ghamdi',
                'phone' => '+966500000005',
                'email' => 'omar@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '177.00',
                'joined_at' => '2026-02-24 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 6,
                'name' => 'Rana Al Qahtani',
                'phone' => '+966500000006',
                'email' => 'rana@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '0.00',
                'joined_at' => '2026-04-02 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 17:31:06',
            ],
            [
                'id' => 7,
                'name' => 'Khalid Al Anazi',
                'phone' => '+966500000007',
                'email' => 'khalid@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '0.00',
                'joined_at' => '2026-04-22 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 17:31:06',
            ],
            [
                'id' => 8,
                'name' => 'Nora Al Subaie',
                'phone' => '+966500000008',
                'email' => 'nora@example.sa',
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'ar',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '0.00',
                'joined_at' => '2026-02-24 17:31:06',
                'created_at' => '2026-05-10 17:30:31',
                'updated_at' => '2026-05-10 17:31:06',
            ],
            [
                'id' => 9,
                'name' => 'Hani Test',
                'phone' => '+966500000099',
                'email' => 'hanitest@example.sa',
                'city' => 'Riyadh',
                'area' => 'Olaya',
                'gender' => 'male',
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 1,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '0.00',
                'joined_at' => '2026-05-10 17:46:59',
                'created_at' => '2026-05-10 17:46:59',
                'updated_at' => '2026-05-10 17:47:17',
            ],
            [
                'id' => 10,
                'name' => 'هاني',
                'phone' => '+966535097129',
                'email' => null,
                'city' => 'Riyadh',
                'area' => 'Al Malqa',
                'gender' => 'male',
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 1,
                'notes' => null,
                'avatar_url' => 'avatars/eCLzrRVPUdLqZ8nOhAsSLD8jELrw3dnlsESFQPEI.jpg',
                'wallet_balance' => '145.00',
                'joined_at' => '2026-05-10 18:04:29',
                'created_at' => '2026-05-10 18:04:29',
                'updated_at' => '2026-07-03 08:49:26',
            ],
            [
                'id' => 11,
                'name' => 'Customer 559809687',
                'phone' => '+966559809687',
                'email' => null,
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '0.00',
                'joined_at' => '2026-06-08 23:51:09',
                'created_at' => '2026-06-08 23:51:09',
                'updated_at' => '2026-06-08 23:51:09',
            ],
            [
                'id' => 12,
                'name' => 'Customer 598761234',
                'phone' => '+966598761234',
                'email' => null,
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '500.00',
                'joined_at' => '2026-06-09 07:57:08',
                'created_at' => '2026-06-09 07:57:08',
                'updated_at' => '2026-06-09 07:57:09',
            ],
            [
                'id' => 13,
                'name' => 'Customer 571112233',
                'phone' => '+966571112233',
                'email' => null,
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '401.00',
                'joined_at' => '2026-06-09 07:58:11',
                'created_at' => '2026-06-09 07:58:11',
                'updated_at' => '2026-06-09 07:58:11',
            ],
            [
                'id' => 14,
                'name' => 'Customer 533344455',
                'phone' => '+966533344455',
                'email' => null,
                'city' => 'Riyadh',
                'area' => null,
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 0,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '201.00',
                'joined_at' => '2026-06-09 08:44:11',
                'created_at' => '2026-06-09 08:44:11',
                'updated_at' => '2026-06-09 08:44:11',
            ],
            [
                'id' => 15,
                'name' => 'Hani',
                'phone' => '+966561234567',
                'email' => null,
                'city' => 'Riyadh',
                'area' => 'Olaya',
                'gender' => null,
                'preferred_language' => 'en',
                'status' => 'active',
                'profile_completed' => 1,
                'notes' => null,
                'avatar_url' => null,
                'wallet_balance' => '250.00',
                'joined_at' => '2026-06-09 15:45:00',
                'created_at' => '2026-06-09 15:45:00',
                'updated_at' => '2026-06-09 15:45:01',
            ],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('customers')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
