<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated data snapshot for `customer_notifications` (44 rows).
 * Regenerated from the live `velto_admin` database.
 */
class CustomerNotificationSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('customer_notifications')->truncate();

        $rows = [
            [
                'id' => 1,
                'customer_id' => 1,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Your wash is scheduled for tomorrow at 10:30.',
                'body_ar' => 'تم جدولة الغسيل غداً الساعة ١٠:٣٠.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-10 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 2,
                'customer_id' => 1,
                'kind' => 'on_the_way',
                'title' => 'Detailer is on the way',
                'title_ar' => 'المتخصص في الطريق',
                'body' => 'Ahmed will arrive in ~10 minutes.',
                'body_ar' => 'سيصل أحمد خلال ١٠ دقائق تقريباً.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-09 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 3,
                'customer_id' => 1,
                'kind' => 'completed',
                'title' => 'Wash completed',
                'title_ar' => 'تم إنجاز الغسيل',
                'body' => 'Tap to rate your experience.',
                'body_ar' => 'اضغط لتقييم التجربة.',
                'data' => null,
                'read_at' => '2026-05-07 20:47:00',
                'created_at' => '2026-05-07 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 4,
                'customer_id' => 1,
                'kind' => 'promo',
                'title' => '20% off your next wash',
                'title_ar' => 'خصم ٢٠٪ على غسيلك القادم',
                'body' => 'Use code VELTO20 this week.',
                'body_ar' => 'استخدم الكود VELTO20 هذا الأسبوع.',
                'data' => null,
                'read_at' => '2026-05-05 20:47:00',
                'created_at' => '2026-05-05 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 5,
                'customer_id' => 2,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Your wash is scheduled for tomorrow at 10:30.',
                'body_ar' => 'تم جدولة الغسيل غداً الساعة ١٠:٣٠.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-10 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 6,
                'customer_id' => 2,
                'kind' => 'on_the_way',
                'title' => 'Detailer is on the way',
                'title_ar' => 'المتخصص في الطريق',
                'body' => 'Ahmed will arrive in ~10 minutes.',
                'body_ar' => 'سيصل أحمد خلال ١٠ دقائق تقريباً.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-09 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 7,
                'customer_id' => 2,
                'kind' => 'completed',
                'title' => 'Wash completed',
                'title_ar' => 'تم إنجاز الغسيل',
                'body' => 'Tap to rate your experience.',
                'body_ar' => 'اضغط لتقييم التجربة.',
                'data' => null,
                'read_at' => '2026-05-07 20:47:00',
                'created_at' => '2026-05-07 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 8,
                'customer_id' => 2,
                'kind' => 'promo',
                'title' => '20% off your next wash',
                'title_ar' => 'خصم ٢٠٪ على غسيلك القادم',
                'body' => 'Use code VELTO20 this week.',
                'body_ar' => 'استخدم الكود VELTO20 هذا الأسبوع.',
                'data' => null,
                'read_at' => '2026-05-05 20:47:00',
                'created_at' => '2026-05-05 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 9,
                'customer_id' => 3,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Your wash is scheduled for tomorrow at 10:30.',
                'body_ar' => 'تم جدولة الغسيل غداً الساعة ١٠:٣٠.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-10 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 10,
                'customer_id' => 3,
                'kind' => 'on_the_way',
                'title' => 'Detailer is on the way',
                'title_ar' => 'المتخصص في الطريق',
                'body' => 'Ahmed will arrive in ~10 minutes.',
                'body_ar' => 'سيصل أحمد خلال ١٠ دقائق تقريباً.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-09 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 11,
                'customer_id' => 3,
                'kind' => 'completed',
                'title' => 'Wash completed',
                'title_ar' => 'تم إنجاز الغسيل',
                'body' => 'Tap to rate your experience.',
                'body_ar' => 'اضغط لتقييم التجربة.',
                'data' => null,
                'read_at' => '2026-05-07 20:47:00',
                'created_at' => '2026-05-07 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 12,
                'customer_id' => 3,
                'kind' => 'promo',
                'title' => '20% off your next wash',
                'title_ar' => 'خصم ٢٠٪ على غسيلك القادم',
                'body' => 'Use code VELTO20 this week.',
                'body_ar' => 'استخدم الكود VELTO20 هذا الأسبوع.',
                'data' => null,
                'read_at' => '2026-05-05 20:47:00',
                'created_at' => '2026-05-05 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 13,
                'customer_id' => 4,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Your wash is scheduled for tomorrow at 10:30.',
                'body_ar' => 'تم جدولة الغسيل غداً الساعة ١٠:٣٠.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-10 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 14,
                'customer_id' => 4,
                'kind' => 'on_the_way',
                'title' => 'Detailer is on the way',
                'title_ar' => 'المتخصص في الطريق',
                'body' => 'Ahmed will arrive in ~10 minutes.',
                'body_ar' => 'سيصل أحمد خلال ١٠ دقائق تقريباً.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-09 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 15,
                'customer_id' => 4,
                'kind' => 'completed',
                'title' => 'Wash completed',
                'title_ar' => 'تم إنجاز الغسيل',
                'body' => 'Tap to rate your experience.',
                'body_ar' => 'اضغط لتقييم التجربة.',
                'data' => null,
                'read_at' => '2026-05-07 20:47:00',
                'created_at' => '2026-05-07 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 16,
                'customer_id' => 4,
                'kind' => 'promo',
                'title' => '20% off your next wash',
                'title_ar' => 'خصم ٢٠٪ على غسيلك القادم',
                'body' => 'Use code VELTO20 this week.',
                'body_ar' => 'استخدم الكود VELTO20 هذا الأسبوع.',
                'data' => null,
                'read_at' => '2026-05-05 20:47:00',
                'created_at' => '2026-05-05 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 17,
                'customer_id' => 5,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Your wash is scheduled for tomorrow at 10:30.',
                'body_ar' => 'تم جدولة الغسيل غداً الساعة ١٠:٣٠.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-10 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 18,
                'customer_id' => 5,
                'kind' => 'on_the_way',
                'title' => 'Detailer is on the way',
                'title_ar' => 'المتخصص في الطريق',
                'body' => 'Ahmed will arrive in ~10 minutes.',
                'body_ar' => 'سيصل أحمد خلال ١٠ دقائق تقريباً.',
                'data' => null,
                'read_at' => null,
                'created_at' => '2026-05-09 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 19,
                'customer_id' => 5,
                'kind' => 'completed',
                'title' => 'Wash completed',
                'title_ar' => 'تم إنجاز الغسيل',
                'body' => 'Tap to rate your experience.',
                'body_ar' => 'اضغط لتقييم التجربة.',
                'data' => null,
                'read_at' => '2026-05-07 20:47:00',
                'created_at' => '2026-05-07 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 20,
                'customer_id' => 5,
                'kind' => 'promo',
                'title' => '20% off your next wash',
                'title_ar' => 'خصم ٢٠٪ على غسيلك القادم',
                'body' => 'Use code VELTO20 this week.',
                'body_ar' => 'استخدم الكود VELTO20 هذا الأسبوع.',
                'data' => null,
                'read_at' => '2026-05-05 20:47:00',
                'created_at' => '2026-05-05 18:47:00',
                'updated_at' => '2026-05-10 18:47:00',
            ],
            [
                'id' => 21,
                'customer_id' => 12,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-06-09 09:00',
                'body_ar' => 'Express exterior wash بتاريخ 2026-06-09 09:00',
                'data' => '{"appointment_id": 1}',
                'read_at' => null,
                'created_at' => '2026-06-09 07:57:08',
                'updated_at' => '2026-06-09 07:57:08',
            ],
            [
                'id' => 22,
                'customer_id' => 13,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-06-09 10:30',
                'body_ar' => 'Express exterior wash بتاريخ 2026-06-09 10:30',
                'data' => '{"appointment_id": 2}',
                'read_at' => null,
                'created_at' => '2026-06-09 07:58:11',
                'updated_at' => '2026-06-09 07:58:11',
            ],
            [
                'id' => 23,
                'customer_id' => 14,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-06-09 14:00',
                'body_ar' => 'Express exterior wash بتاريخ 2026-06-09 14:00',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-09 08:44:11',
                'updated_at' => '2026-06-09 08:44:11',
            ],
            [
                'id' => 24,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-13 22:58:03',
                'updated_at' => '2026-06-13 22:58:03',
            ],
            [
                'id' => 25,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-13 22:58:03',
                'updated_at' => '2026-06-13 22:58:03',
            ],
            [
                'id' => 26,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-13 23:34:23',
                'updated_at' => '2026-06-13 23:34:23',
            ],
            [
                'id' => 27,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-13 23:34:25',
                'updated_at' => '2026-06-13 23:34:25',
            ],
            [
                'id' => 28,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 06:39:03',
                'updated_at' => '2026-06-24 06:39:03',
            ],
            [
                'id' => 29,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 06:39:05',
                'updated_at' => '2026-06-24 06:39:05',
            ],
            [
                'id' => 30,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 06:41:58',
                'updated_at' => '2026-06-24 06:41:58',
            ],
            [
                'id' => 31,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 06:42:14',
                'updated_at' => '2026-06-24 06:42:14',
            ],
            [
                'id' => 32,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:39:55',
                'updated_at' => '2026-06-24 07:39:55',
            ],
            [
                'id' => 33,
                'customer_id' => 14,
                'kind' => 'arrived',
                'title' => 'Your specialist has arrived',
                'title_ar' => 'وصل الفني',
                'body' => 'Express exterior wash — your specialist has arrived.',
                'body_ar' => 'Express exterior wash — وصل الفني إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:39:55',
                'updated_at' => '2026-06-24 07:39:55',
            ],
            [
                'id' => 34,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:39:55',
                'updated_at' => '2026-06-24 07:39:55',
            ],
            [
                'id' => 35,
                'customer_id' => 14,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:44:09',
                'updated_at' => '2026-06-24 07:44:09',
            ],
            [
                'id' => 36,
                'customer_id' => 14,
                'kind' => 'arrived',
                'title' => 'Your specialist has arrived',
                'title_ar' => 'وصل الفني',
                'body' => 'Express exterior wash — your specialist has arrived.',
                'body_ar' => 'Express exterior wash — وصل الفني إليك.',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:44:31',
                'updated_at' => '2026-06-24 07:44:31',
            ],
            [
                'id' => 37,
                'customer_id' => 14,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 3}',
                'read_at' => null,
                'created_at' => '2026-06-24 07:45:26',
                'updated_at' => '2026-06-24 07:45:26',
            ],
            [
                'id' => 38,
                'customer_id' => 10,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-07-04 09:00',
                'body_ar' => 'Express exterior wash بتاريخ 2026-07-04 09:00',
                'data' => '{"appointment_id": 4}',
                'read_at' => null,
                'created_at' => '2026-07-03 06:29:42',
                'updated_at' => '2026-07-03 06:29:42',
            ],
            [
                'id' => 39,
                'customer_id' => 10,
                'kind' => 'on_the_way',
                'title' => 'Your specialist is on the way',
                'title_ar' => 'الفني في الطريق إليك',
                'body' => 'Express exterior wash — your specialist is heading to you.',
                'body_ar' => 'Express exterior wash — الفني في طريقه إليك.',
                'data' => '{"appointment_id": 4}',
                'read_at' => null,
                'created_at' => '2026-07-03 06:38:08',
                'updated_at' => '2026-07-03 06:38:08',
            ],
            [
                'id' => 40,
                'customer_id' => 10,
                'kind' => 'arrived',
                'title' => 'Your specialist has arrived',
                'title_ar' => 'وصل الفني',
                'body' => 'Express exterior wash — your specialist has arrived.',
                'body_ar' => 'Express exterior wash — وصل الفني إليك.',
                'data' => '{"appointment_id": 4}',
                'read_at' => null,
                'created_at' => '2026-07-03 06:38:08',
                'updated_at' => '2026-07-03 06:38:08',
            ],
            [
                'id' => 41,
                'customer_id' => 10,
                'kind' => 'completed',
                'title' => 'Service completed',
                'title_ar' => 'تم إنجاز الخدمة',
                'body' => 'Express exterior wash is done. Thank you for choosing Velto!',
                'body_ar' => 'تم إنجاز Express exterior wash. شكراً لاختيارك فيلتو!',
                'data' => '{"appointment_id": 4}',
                'read_at' => null,
                'created_at' => '2026-07-03 06:38:08',
                'updated_at' => '2026-07-03 06:38:08',
            ],
            [
                'id' => 42,
                'customer_id' => 10,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-07-05 10:30',
                'body_ar' => 'Express exterior wash بتاريخ 2026-07-05 10:30',
                'data' => '{"appointment_id": 5}',
                'read_at' => null,
                'created_at' => '2026-07-03 07:45:09',
                'updated_at' => '2026-07-03 07:45:09',
            ],
            [
                'id' => 43,
                'customer_id' => 10,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Express exterior wash on 2026-07-04 09:00',
                'body_ar' => 'Express exterior wash بتاريخ 2026-07-04 09:00',
                'data' => '{"appointment_id": 6}',
                'read_at' => null,
                'created_at' => '2026-07-03 08:47:44',
                'updated_at' => '2026-07-03 08:47:44',
            ],
            [
                'id' => 44,
                'customer_id' => 10,
                'kind' => 'booking',
                'title' => 'Booking confirmed',
                'title_ar' => 'تم تأكيد الحجز',
                'body' => 'Interior detail on 2026-07-04 10:30',
                'body_ar' => 'Interior detail بتاريخ 2026-07-04 10:30',
                'data' => '{"appointment_id": 7}',
                'read_at' => null,
                'created_at' => '2026-07-03 08:47:45',
                'updated_at' => '2026-07-03 08:47:45',
            ],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('customer_notifications')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
