<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated data snapshot for `vehicle_model_entries` (48 rows).
 * Regenerated from the live `velto_admin` database.
 */
class VehicleModelEntrySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('vehicle_model_entries')->truncate();

        $rows = [
            [
                'id' => 1,
                'vehicle_brand_id' => 1,
                'name' => 'Camry',
                'name_ar' => 'كامري',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 2,
                'vehicle_brand_id' => 1,
                'name' => 'Corolla',
                'name_ar' => 'كورولا',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 3,
                'vehicle_brand_id' => 1,
                'name' => 'Land Cruiser',
                'name_ar' => 'لاند كروزر',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 4,
                'vehicle_brand_id' => 1,
                'name' => 'Hilux',
                'name_ar' => 'هايلكس',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 5,
                'vehicle_brand_id' => 1,
                'name' => 'RAV4',
                'name_ar' => 'راف فور',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 6,
                'vehicle_brand_id' => 1,
                'name' => 'Yaris',
                'name_ar' => 'يارس',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 7,
                'vehicle_brand_id' => 1,
                'name' => 'Prado',
                'name_ar' => 'برادو',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 8,
                'vehicle_brand_id' => 1,
                'name' => 'Avalon',
                'name_ar' => 'أفالون',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 9,
                'vehicle_brand_id' => 2,
                'name' => 'ES',
                'name_ar' => 'اي اس',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 10,
                'vehicle_brand_id' => 2,
                'name' => 'IS',
                'name_ar' => 'آي اس',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 11,
                'vehicle_brand_id' => 2,
                'name' => 'LS',
                'name_ar' => 'ال اس',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 12,
                'vehicle_brand_id' => 2,
                'name' => 'LX',
                'name_ar' => 'ال اكس',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 13,
                'vehicle_brand_id' => 2,
                'name' => 'NX',
                'name_ar' => 'ان اكس',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 14,
                'vehicle_brand_id' => 2,
                'name' => 'RX',
                'name_ar' => 'آر اكس',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 15,
                'vehicle_brand_id' => 2,
                'name' => 'UX',
                'name_ar' => 'يو اكس',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 16,
                'vehicle_brand_id' => 2,
                'name' => 'GX',
                'name_ar' => 'جي اكس',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 17,
                'vehicle_brand_id' => 3,
                'name' => 'Sonata',
                'name_ar' => 'سوناتا',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 18,
                'vehicle_brand_id' => 3,
                'name' => 'Elantra',
                'name_ar' => 'النترا',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 19,
                'vehicle_brand_id' => 3,
                'name' => 'Accent',
                'name_ar' => 'اكسنت',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 20,
                'vehicle_brand_id' => 3,
                'name' => 'Tucson',
                'name_ar' => 'توسان',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 21,
                'vehicle_brand_id' => 3,
                'name' => 'Santa Fe',
                'name_ar' => 'سنتافي',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 22,
                'vehicle_brand_id' => 3,
                'name' => 'Kona',
                'name_ar' => 'كونا',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 23,
                'vehicle_brand_id' => 3,
                'name' => 'Palisade',
                'name_ar' => 'باليسيد',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 24,
                'vehicle_brand_id' => 3,
                'name' => 'Azera',
                'name_ar' => 'ازيرا',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 25,
                'vehicle_brand_id' => 4,
                'name' => 'Altima',
                'name_ar' => 'التيما',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 26,
                'vehicle_brand_id' => 4,
                'name' => 'Sunny',
                'name_ar' => 'صني',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 27,
                'vehicle_brand_id' => 4,
                'name' => 'Maxima',
                'name_ar' => 'ماكسيما',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 28,
                'vehicle_brand_id' => 4,
                'name' => 'Patrol',
                'name_ar' => 'باترول',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 29,
                'vehicle_brand_id' => 4,
                'name' => 'X-Trail',
                'name_ar' => 'اكس تريل',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 30,
                'vehicle_brand_id' => 4,
                'name' => 'Sentra',
                'name_ar' => 'سنترا',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 31,
                'vehicle_brand_id' => 4,
                'name' => 'Pathfinder',
                'name_ar' => 'باثفايندر',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 32,
                'vehicle_brand_id' => 4,
                'name' => 'Kicks',
                'name_ar' => 'كيكس',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 33,
                'vehicle_brand_id' => 5,
                'name' => 'C-Class',
                'name_ar' => 'الفئة C',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 34,
                'vehicle_brand_id' => 5,
                'name' => 'E-Class',
                'name_ar' => 'الفئة E',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 35,
                'vehicle_brand_id' => 5,
                'name' => 'S-Class',
                'name_ar' => 'الفئة S',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 36,
                'vehicle_brand_id' => 5,
                'name' => 'GLA',
                'name_ar' => 'جي ال ايه',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 37,
                'vehicle_brand_id' => 5,
                'name' => 'GLC',
                'name_ar' => 'جي ال سي',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 38,
                'vehicle_brand_id' => 5,
                'name' => 'GLE',
                'name_ar' => 'جي ال اي',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 39,
                'vehicle_brand_id' => 5,
                'name' => 'GLS',
                'name_ar' => 'جي ال اس',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 40,
                'vehicle_brand_id' => 5,
                'name' => 'G-Class',
                'name_ar' => 'الفئة G',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 41,
                'vehicle_brand_id' => 6,
                'name' => '3 Series',
                'name_ar' => 'الفئة الثالثة',
                'sort_order' => 0,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 42,
                'vehicle_brand_id' => 6,
                'name' => '5 Series',
                'name_ar' => 'الفئة الخامسة',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 43,
                'vehicle_brand_id' => 6,
                'name' => '7 Series',
                'name_ar' => 'الفئة السابعة',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 44,
                'vehicle_brand_id' => 6,
                'name' => 'X1',
                'name_ar' => 'اكس 1',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 45,
                'vehicle_brand_id' => 6,
                'name' => 'X3',
                'name_ar' => 'اكس 3',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 46,
                'vehicle_brand_id' => 6,
                'name' => 'X5',
                'name_ar' => 'اكس 5',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 47,
                'vehicle_brand_id' => 6,
                'name' => 'X6',
                'name_ar' => 'اكس 6',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
            [
                'id' => 48,
                'vehicle_brand_id' => 6,
                'name' => 'X7',
                'name_ar' => 'اكس 7',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2026-05-10 19:19:56',
                'updated_at' => '2026-05-10 19:19:56',
            ],
        ];

        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('vehicle_model_entries')->insert($chunk);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
